### ISSUE TITLE
Update profile endpoints to fetch given user's profile

### ISSUE THREAD

**Issue by NasihNazeem** [Project-Chirp/chirp-backend#41]
Currently, the profile route endpoints only look for the active user's tweets, likes, replies. We want to update these routes so that they can take a username query parameter and look that user's profile up. For example, the `/user1` route should return the profile information for the person with username `user1`

**Comment by Dennull** [comment]
There was a mix up with this ticket and #42. This ticket refers to changing the profile routes from using userId's to using usernames. #42 refers to the endpoints for users to edit their profile details when using the edit profile modal. I'm reopening this ticket
